### ISSUE TITLE
Horaires de ligne - liste des lignes d'un réseau tronquée

### ISSUE THREAD

**Issue by prhod** [CanalTP/navitia-explorer#10]
Après la seleciton d'un réseau la liste des lignes est tronquée à 25 items

**Comment by nlehuby** [comment]
La liste des réseaux aussi ;)

**Comment by prhod** [comment]
fixed by https://github.com/CanalTP/navitia-explorer/pull/11
Je n'ai fait que monter la limite par défaut à 1000, la gestion avancée du pager étant beaucoup plus compliquée à gérer en JS
