### ISSUE TITLE
Remove PHP dependency (only HTML/JS Site)

### ISSUE THREAD

**Issue by prhod** [CanalTP/navitia-explorer#15]

**Comment by TeXitoi** [comment]
It'll be great!

**Comment by prhod** [comment]
Coverage page is modified to use only JS. Others will follow ...

**Comment by prhod** [comment]
Work almost complete in https://github.com/CanalTP/navitia-explorer/tree/php_dependency.
There seems to be a limitation with the Tyr web service for cross domain JS call.

**Comment by TeXitoi** [comment]
It's possible that tyr ws is not cross domain. You can open an issue on navitia.

It's working great. I still have 2 problems:
 * it's not working on a https server.
 * if you look at the url, you can see the token. That's not needed as it is in params.json, and everyone can see my token without searching too hard...

**Comment by TeXitoi** [comment]
Ha, and url injection doesn't work. We'll need something to inject some arguments to the api (using undocumented or still-in-development arguments.

**Comment by prhod** [comment]
I fixed the issues you pointed out. Tell me if the are still issues going on :)

**Comment by TeXitoi** [comment]
The URL link on "itinéraire" feature doesn't work.

**Comment by TeXitoi** [comment]
It's working on a https server, the  token is no more visible in the url, and url injection is "working" back.

**Comment by prhod** [comment]
Everything fixed and PR https://github.com/CanalTP/navitia-explorer/pull/17
This issue is still going on until the migration of the Tyr API.

**Comment by TeXitoi** [comment]
fixed by #18
